CREATE TABLE table_products
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name            TEXT                                                 NOT NULL CHECK ( name != '' ),
    description     TEXT                                                 NOT NULL CHECK ( description != '' ),
    series          TEXT                                                 NOT NULL CHECK ( series != '' ),
    type_id         INTEGER                                              NOT NULL,
    unit_id         INTEGER                                              NOT NULL,
    manufacturer_id INTEGER                                              NOT NULL,
    purchase_price  NUMERIC(7, 2)                                        NOT NULL CHECK ( purchase_price > 0),
    selling_price   NUMERIC(7, 2)                                        NOT NULL CHECK ( selling_price > purchase_price ),
    unit_value      NUMERIC(10, 2)                                       NOT NULL CHECK ( unit_value > 0 ),
    production_date DATE                                                 NOT NULL,
    expiration_date DATE                                                 NOT NULL CHECK ( expiration_date > production_date ),
    FOREIGN KEY (type_id) REFERENCES table_types (id),
    FOREIGN KEY (unit_id) REFERENCES table_units (id),
    FOREIGN KEY (manufacturer_id) REFERENCES table_manufacturers (id)
);

-- Таблицы продаж
CREATE TABLE table_salespoint
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name    TEXT                                                 NOT NULL CHECK ( name != '' ),
    address TEXT                                                 NOT NULL CHECK ( address != '' )
);

CREATE TABLE table_online_purchases
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    product_code           INTEGER                                              NOT NULL,
    id_delivery_salespoint INTEGER                                              NOT NULL,
    payment                PAYMENT_METHOD                                       NOT NULL,
    FOREIGN KEY (id_delivery_salespoint) REFERENCES table_salespoint (id)
);

CREATE TABLE table_offline_purchases
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    salespoint_id INTEGER,
    client_id     INTEGER                                              NOT NULL DEFAULT 0,
    employee_id   INTEGER                                              NOT NULL,
    FOREIGN KEY (client_id) REFERENCES table_clients (id),
    FOREIGN KEY (employee_id) REFERENCES table_employees (id),
    FOREIGN KEY (salespoint_id) REFERENCES table_salespoint (id)
);

CREATE TABLE table_purchases
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    product_id          INTEGER                                              NOT NULL,
    purchase_date       DATE                                                 NOT NULL,
    online_purchase_id  INTEGER CHECK ( online_purchase_id IS NULL OR online_purchase_id = 0 ) DEFAULT 0,
    offline_purchase_id INTEGER CHECK ( offline_purchase_id IS NULL OR offline_purchase_id = 0 ) DEFAULT 0,
    FOREIGN KEY (online_purchase_id) REFERENCES table_online_purchases (id),
    FOREIGN KEY (offline_purchase_id) REFERENCES table_offline_purchases (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);